# .readthedocs.yml
# Read the Docs configuration file

# Required
version: 2

# Build HTML format only for faster builds
formats:
  - html

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

# Install the package (and its "docs" extra) from pyproject.toml
python:
  install:
    - method: pip
      path: .
      extra_requirements:
          - docs
