# .readthedocs.yml
# Read the Docs configuration file

# Required
version: 2

# Build all formats
formats: all

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

build:
  image: latest

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
          - docs
